
version: '3'

services:
  app:
    image: minesweeper:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 4200:4200
    volumes:
      - .:/minesweeper